### ISSUE TITLE
how to install ps2pdf command in windows?

### ISSUE THREAD

**Issue by shizhou726** [mkvoya/eps-preview#12]
I don't know where to download...

**Comment by mkvoya** [comment]
I don't have Windows devices at hand ... But I think there are some options you can try:
- Download the binary via Cygwin or MSys2?
- WSL?

There is also an email showing how to write a bat file invoking ghostscript: https://ghostscript.com/pipermail/gs-devel/2009-April/008314.html
As far as I know, ghostscript is fairly easy to install on Windows.

**Comment by shizhou726** [comment]
thank you very much

**Comment by DoHaiSon** [comment]
I faced to this problem on windows.
I installed both pdf2svg for windows and ghostscript  as well. Both of them are added to env path of windows, so on terminal of VSCode, I can call ps2pdf and pdf2svg. But after opening Preview eps, the error below appeared:
`Failed to execute pdf2svg, is that installed?`
