### ISSUE TITLE
No "preview" icon in Visual Studio panel

### ISSUE THREAD

**Issue by kevinrue** [mkvoya/eps-preview#15]
The toolbar does not show the button that is clicked in the demo GIF. 

![image](https://user-images.githubusercontent.com/5769108/223373307-965c76c1-49da-42f7-a2c8-f20addb8237c.png)

I'm using VSCode installed on a Macbook, and I'm opening a remote EPS file using the 'Remote - SSH' VSCode plugin distributed by Microsoft.

Any thought? Thanks in advance!

**Comment by mkvoya** [comment]
This extension depends on the `PostScript Language` extension to recognize an EPS file. Please check whether you have the extension installed. :)

I checked that the extension works fine in my VSCode.
---
My vscode version info:
Version: 1.77.0-insider
Commit: bbc87d8ec2453f12c0066e1c30b41cd5bd2aa021
Date: 2023-03-07T05:25:27.031Z (23 hrs ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: Yes

**Comment by kevinrue** [comment]
Thanks! Problem solved then.On 8 Mar 2023, at 05:06, Mingkai Dong ***@***.***> wrote:﻿
This extension depends on the PostScript Language extension to recognize an EPS file. Please check whether you have the extension installed. :)
I checked that the extension works fine in my VSCode.
My vscode version info:
Version: 1.77.0-insider
Commit: bbc87d8ec2453f12c0066e1c30b41cd5bd2aa021
Date: 2023-03-07T05:25:27.031Z (23 hrs ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.3.0
Sandboxed: Yes
