### ISSUE TITLE
Eps Preview on dark mode is illegible

### ISSUE THREAD

**Issue by 123epsilon** [mkvoya/eps-preview#16]
Hi, when using darkmode color themes in VSCode I can't see the eps figures I generate without changing to a light color theme. Is there a way to explicitly set the background color of the preview window to white? For instance something like: "eps-preview.preview.background": "#FFFFFF"

**Comment by wintervolcano** [comment]
Is there any fix for this issue?

**Comment by mkvoya** [comment]
This issue is resolved in the latest v0.5.0 version.

**Comment by wintervolcano** [comment]
Thank you! That was quick!
